config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
        
  get '/profile', to: 'users#show', as: 'profile'
  get '/contacts', to: 'users#index', as: 'contacts'
  
  resources :chats do
    resources :messages
  end
    
  devise_for :users
    
  root to: 'chats#index'
  
  #Mount websocket connection    
  mount ActionCable.server => '/cable'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :sender, foreign_key: :sender_id, class_name: :User
    belongs_to :recipient, foreign_key: :recipient_id, class_name: :User
    has_many :messages, dependent: :destroy 

    validates_presence_of :sender_id, :recipient_id
    validates_uniqueness_of :sender_id, :scope => :recipient_id
    
    scope :between, -> (sender_id,recipient_id) do
        where("(chats.sender_id = :sender AND chats.recipient_id = :receiver)
                OR (chats.sender_id = :receiver AND chats.recipient_id = :sender)",
                sender: sender_id, receiver: recipient_id
            )
    end
    
    def read(user) #Marks all readable messages by a user as read
        messages.unread(user.id).each do |message|
            message.update(read: true)
        end
    end
    
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user, foreign_key: :user_id
    belongs_to :chat
    
    after_create_commit {MessageBroadcastJob.perform_now self}
    
    validates_presence_of :text, :chat_id, :user_id
    
    scope :unread, -> (user_id) do
        where("messages.read =? AND messages.user_id !=?", false, user_id)
  	end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #:timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable

  validates :name, presence: true    
    
  scope :confirmed, -> { where("confirmed_at IS NOT NULL") }
    
  def chats
      Chat.where("sender_id = ? OR recipient_id = ?", self.id, self.id)
  end
    
  def notifications #Number of conversations with unread messages by the user
        a = chats.map do |chat| 
            chat.id if chat.messages.unread(id).any?  
        end
        a.compact
  end    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
    
    def index
        if !user_signed_in?
            redirect_to new_user_session_path
        else
            @chats = current_user.chats.order('updated_at DESC')
            respond_to do |format|
              format.html do
                  session[:last_page] = chats_path
                  if last_chat = Chat.find_by(id: session[:chat_id])
                     last_chat.read(current_user)
                    session[:chat_id] = nil
                  end
                end
              format.json { render json: @chats }
            end
        end
    end
    
    def create
        if @chat = Chat.between(params[:sender_id], params[:recipient_id]).present?
            @chat = Chat.between(params[:sender_id], params[:recipient_id]).first
        else
            @chat = Chat.create(chat_params)
        end
        redirect_to chat_messages_path(@chat)
    end
    
    private
    
        def chat_params
            params.permit(:recipient_id, :sender_id)        
        end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    
    def index
        @chat = Chat.find(params[:chat_id])
        @message = @chat.messages.new
        @messages = @chat.messages
        session[:chat_id] = @chat.id
        @chat.read(current_user)
        puts session[:last_page]
    end
    
    def create
        @chat = Chat.find(params[:chat_id])
        @message = @chat.messages.build(message_params)
        if @message.save
            #Chats are ordered based on recent activity
            @chat.touch 
            head :ok
        end
    end
    
    private
    
        def message_params
            params.require('message').permit(:text, :user_id)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :delete_empty_chat, :remove_notifications, only: :index
    
    def index
        if !user_signed_in?
            redirect_to new_user_session_path
        else
            @users = User.order('name')
            session[:last_page] = contacts_path
            puts session[:last_page]
        end
    end
    
    def show
        if !user_signed_in?
            redirect_to new_user_session_path
        end
    end
    
    private
    
        def delete_empty_chat
            if last_chat = Chat.find_by(id: session[:chat_id])
                last_chat.delete if last_chat.messages.count == 0
            end
        end
    
        def remove_notifications
            if last_chat = Chat.find_by(id: session[:chat_id])
                last_chat.read(current_user)
                session[:chat_id] = nil
            end
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

    def other_user(chat)
        current_user.id == chat.sender.id ?  chat.recipient : chat.sender
    end

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def avatar(user)
        user.avatar_url || "default.png"
    end
end

app/views/chats/_chat_item.html.erb
<% if chat.messages.any? %>
	<%= link_to chat_messages_path(chat.id), id: "chat-#{chat.id}" ,class: "chat" do %>
		<div class= "user-thumbnail">
			<%= image_tag avatar(other_user(chat)) %>
			<div class="chat-notify">
				<% if chat.messages.unread(current_user.id).any? %>
					<div class="notification"> 1 </div>
				<% end %>
			</div>	
		</div>
		<div class= "last-msg">
			<h4><%= other_user(chat).name %></h4>
			<p class="truncate">
				<%= icon("reply") if current_user.id == chat.messages.last.user_id %>
				<%= chat.messages.last.text %>
			</p>
		</div>
		<div class= "date">
			<p><%= chat.messages.last.created_at.strftime("%b %d") %></p>
			<p><%= chat.messages.last.created_at.strftime("%l:%M%p") %></p>
		</div>
	<% end %>
	<hr>
<% end %>

app/views/chats/_welcome.html.erb
<%= image_tag "realtalk.png", class: "medium-logo" %>
<h4>Welcome to Realtalk <%= current_user.name %></h4>
<p>You currently have no chats. To start a chat, click on Contacts and choose someone to talk to.</p>
<p>Quick note, realtime notifications aren't working yet for brand new chats. But once a chat exists, everything should work fine!</p>
<div class="instructions">
	<h3>Contacts</h3>
	<%= icon("arrow-down")%>
</div>

app/views/chats/index.html.erb
<% content_for :navbar_contents do %>
	<ul class="nav-center">
	  <li><%= icon('comment') %></span>&nbsp;<span>Chats</span></li>
	</ul>
<% end %>

<% content_for :footer_contents do %>
	<%= render '/shared/standard_footer' %>
<% end %>

<div class = "chat-list">
	<% if @chats.any? %>
		<% @chats.each do |chat| %>
			<%= render partial: "chat_item", locals: { chat: chat } %>
		<% end %>
	<% else %>
		<%= render 'welcome' %>
	<% end %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Realtalk</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta id="meta" name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>

  <body>

    <nav class="nav-mobile">
      <div class="container-fluid">
        <%= yield :navbar_contents %>
      </div>
    </nav>

  	<div class="container">
  		<% flash.each do |key, value| %>
    		<div class="alert alert-<%= key %>">
      			<%= value %>
    		</div>
  		<% end %>
	</div>

	<div class="container-fluid main-content">
	  <%= yield %>
	</div>

  <footer class="footer-mobile">
    <div class="container-fluid">
      <%= yield :footer_contents %>
    </div>
  </footer>

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Realtalk</title>
    <%= csrf_meta_tags %>
    <meta id="meta" name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<div class="container">
  		<% flash.each do |key, value| %>
    		<div class="alert alert-<%= key %>">
      			<%= value %>
    		</div>
  		<% end %>
	</div>


	<div class="container">
    <div class= "login-container">
    <%= image_tag "realtalk.png", class: "medium-logo"%>
    <%= yield %>
    </div>
  <%= image_tag "town.png", class: "footer-img"%>
  </div>

  </body>
</html>

app/views/messages/_message.html.erb
<% if msg.text.present? %>
	<% if msg.user_id == current_user.id %>
		<p class="current-user msg"><%= msg.text %></p>
	<% else %>
		<p class="other-user msg"><%= msg.text %></p>
	<% end %>
<% end %>

app/views/messages/index.html.erb
<% content_for :navbar_contents do %>
	<ul class="nav-left">
	  <li><%= link_to icon('arrow-left'), session[:last_page] %></span></li>
	</ul>
	<ul class="nav-center">
	  <li><span><%= other_user(@chat).name %></span></li>
	</ul>
<% end %>

<% content_for :footer_contents do %>
	<ul>
	  <li>
	  	<div class="msg-input">
	  	<%= form_for [@chat, @message], remote: true do |f| %>
	  		<%= f.hidden_field :user_id, value: current_user.id %>
      		<%= f.text_field :text, class: "form-control", placeholder: "Write your message...", autofocus: true %>
        	<%= f.submit "Send", class: "realtalk-btn btn btn-primary" %>
    	<% end %>
    	</div>
	  </li>
	</ul>
<% end %>

<div id="messages" class = "chat-window" data-chat-id = <%= @chat.id %>>
	<% @messages.each do |msg| %>
		<%= render partial: 'message', locals: {msg: msg} %>
	<% end %>
<div>

app/views/pages/chats.html.erb
<% content_for :navbar_contents do %>
	<ul class="nav-center">
	  <li><%= icon('comment') %></span>&nbsp;<span>Chats</span></li>
	</ul>
<% end %>

<% content_for :footer_contents do %>
	<%= render '/shared/standard_footer' %>
<% end %>

<div class = "chat-list">
	<% 10.times do %>
		<%= link_to chat_path, class: "chat" do %>
			<div class= "user-thumbnail">
				<%= image_tag "profile1.jpg" %>	
			</div>
			<div class= "last-msg">
				<h4>Username</h4>
				<p class="truncate">I just wanted to say hello! and also some other stuff, it'll probably get a bit long... Actually i'm not even done yet, let's see if I can push this baby all the way down</p>
			</div>
			<div class= "date">
				<p>OCT 10</p>
				<p>2:24am</p>
			</div>
		<% end %>
		<hr>
	<% end %>
<div>

app/views/pages/contacts.html.erb
<% content_for :navbar_contents do %>
	<ul class="nav-center">
	  <li><%= icon('user') %>&nbsp;<span>Contacts</span></li>
	</ul>
<% end %>

<% content_for :footer_contents do %>
	<%= render '/shared/standard_footer' %>
<% end %>

<div class = "contact-list">
	<% 10.times do %>
		<div class= "contact">
			<div class= "user-thumbnail">
				<%= image_tag "profile1.jpg" %>	
			</div>
			<div class= "user-info">
				<h4>Username</h4>
				<p>User email</p>
			</div>
		</div>
		<hr>
	<% end %>
<div>

app/views/pages/profile.html.erb
<% content_for :navbar_contents do %>
	<ul class="nav-center">
	  <li><%= icon('cog') %></span>&nbsp;<span>Profile</span></li>
	</ul>
<% end %>

<% content_for :footer_contents do %>
	<%= render '/shared/standard_footer' %>
<% end %>

<div class = "profile-header">
	<div class= "user-thumbnail">
		<%= image_tag "profile1.jpg" %>	
	</div>
	<h3>Username</h3>
	<%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "realtalk-btn btn btn-primary btn-lg" %>
</div>
<hr>
<div class = "personal-info">
	<div class="field">Username:</div>
	<div class="value">username</div>
	<div class="edit"><%= link_to icon('edit'), "#", class: "btn realtalk-btn btn-primary" %></div>
</div>
<hr>
<div class = "personal-info">
	<div class="field">Email:</div>
	<div class="value">email@gmail.com</div>
	<div class="edit"><%= link_to icon('edit'), "#", class: "btn realtalk-btn btn-primary" %></div>
</div>
<hr>
<div class = "personal-info">
	<div class="field">Password:</div>
	<div class="value">password</div>
	<div class="edit"><%= link_to icon('edit'), "#", class: "btn realtalk-btn btn-primary" %></div>
</div>
<hr>

app/views/shared/_standard_footer.html.erb
<ul>
  <li><a href=<%= contacts_path %>><%= icon('user') %></a></li>
  <li>
    <a class="msg-icon" href=<%= chats_path %>>
      <%= icon('comment') %>
      <div id="notification-container">
      <% if current_user.notifications.any? %>
          <div class="notification">
            <%= current_user.notifications.count %>
          </div>
      <% end %>
      </div>
    </a>
  </li>
  <li><a href=<%= profile_path %>><%= icon('cog') %></a></li>
</ul>

app/views/users/index.html.erb
<% content_for :navbar_contents do %>
	<ul class="nav-center">
	  <li><%= icon('user') %>&nbsp;<span>Contacts</span></li>
	</ul>
<% end %>

<% content_for :footer_contents do %>
	<%= render '/shared/standard_footer' %>
<% end %>

<div class = "contact-list">
	<% @users.each do |contact| %>
		<% if contact.id != current_user.id %>
		<%= link_to chats_path(sender_id: current_user.id, recipient_id: contact.id), method: "post" do %>
		<div class= "contact">
			<div class= "user-thumbnail">
				<%= image_tag avatar(contact) %>
			</div>
			<div class= "user-info">
				<h4><%= contact.name %></h4>
				<p><%= contact.email %></p>
			</div>
		</div>
		<% end %>
		<hr>
		<% end %>
	<% end %>
</div>

app/views/users/show.html.erb
<% content_for :navbar_contents do %>
	<ul class="nav-center">
	  <li><%= icon('cog') %></span>&nbsp;<span>Profile</span></li>
	</ul>
<% end %>

<% content_for :footer_contents do %>
	<%= render '/shared/standard_footer' %>
<% end %>

<div class = "profile-header">
	<div class= "user-thumbnail">
		<%= image_tag avatar(current_user) %>	
	</div>
	<h3><%= current_user.name %></h3>
	<%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "realtalk-btn btn btn-primary btn-lg" %>
</div>
<hr>
<div class = "personal-info">
	<div class="field">Username:</div>
	<div class="value"><%= current_user.name %></div>
	<div class="edit"><%= link_to icon('edit'), "#", class: "btn realtalk-btn btn-primary" %></div>
</div>
<hr>
<div class = "personal-info">
	<div class="field">Email:</div>
	<div class="value"><%= current_user.email %></div>
	<div class="edit"><%= link_to icon('edit'), "#", class: "btn realtalk-btn btn-primary" %></div>
</div>
<hr>
<div class = "personal-info">
	<div class="field">Password:</div>
	<div class="value">xxxxxxxx</div>
	<div class="edit"><%= link_to icon('edit'), "#", class: "btn realtalk-btn btn-primary" %></div>
</div>
<hr>